from .settings import (
    CLAUDE_API_KEY,
    ELEVENLABS_API_KEY,
    VIDEO_OUTPUT_DIR,
    SCRIPT_OUTPUT_DIR,
    PLATFORMS,
    ACCOUNTS,
    SUPPORTED_LANGUAGES
)

__all__ = [
    'CLAUDE_API_KEY',
    'ELEVENLABS_API_KEY',
    'VIDEO_OUTPUT_DIR',
    'SCRIPT_OUTPUT_DIR',
    'PLATFORMS',
    'ACCOUNTS',
    'SUPPORTED_LANGUAGES'
]
